// 高考AI报学校 - 学校数据库
// 数据为示例数据，仅供参考

const SCHOOLS_DB = [
  {
    id: 1,
    name: "清华大学",
    tier: "985/211/双一流",
    rank: 1,
    city: "北京",
    province: "北京",
    lat: 40.0095,
    lng: 116.3264,
    minScore: 680,
    tags: ["综合", "工科强校", "理科顶尖"],
    majors: ["计算机科学与技术", "电子信息工程", "自动化", "经济管理", "建筑学", "机械工程", "土木工程"],
    strengths: ["计算机", "电子", "自动化", "经管", "建筑"],
    teacherStrength: 98,
    campusEnv: 95,
    dormitory: 75,
    genderRatio: { male: 62, female: 38 },
    foodRating: 88,
    entertainment: 85,
    employmentRate: 98.2,
    avgSalary: "18,000+",
    description: "清华大学是中国最顶尖的综合性研究型大学之一，以工科见长，理科、管理、人文等学科也有极高水准。校园位于北京海淀区，毗邻圆明园，环境优美。",
    campusImages: [
      "https://images.unsplash.com/photo-1562774053-701939374585?w=600",
      "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600"
    ],
    dormitoryDesc: "四人/三人间为主，有空调和暖气，部分楼栋有独立卫浴。紫荆公寓条件较好。",
    foodDesc: "食堂数量众多，桃李园、紫荆园、清芬园等各有特色。北京烤鸭、麻辣香锅等应有尽有。",
    cityDesc: "北京，首都。文化底蕴深厚，就业机会丰富，但生活成本较高。冬季较冷，夏季炎热。",
    pros: ["学术顶尖", "就业极好", "校友资源丰富", "国际化程度高"],
    cons: ["竞争激烈", "压力大", "生活成本高"]
  },
  {
    id: 2,
    name: "北京大学",
    tier: "985/211/双一流",
    rank: 2,
    city: "北京",
    province: "北京",
    lat: 39.9869,
    lng: 116.3059,
    minScore: 678,
    tags: ["综合", "文理强校", "医学顶尖"],
    majors: ["数学", "物理", "中文", "法学", "经济学", "临床医学", "国际关系"],
    strengths: ["数学", "中文", "法学", "经济", "医学"],
    teacherStrength: 97,
    campusEnv: 96,
    dormitory: 72,
    genderRatio: { male: 48, female: 52 },
    foodRating: 86,
    entertainment: 83,
    employmentRate: 97.8,
    avgSalary: "17,500+",
    description: "北京大学是中国近代第一所国立综合性大学，以文科、理科、医学见长。未名湖、博雅塔是标志性景观，学术氛围浓厚。",
    campusImages: [
      "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=600",
      "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=600"
    ],
    dormitoryDesc: "四人/三人间为主，有空调暖气。部分楼栋较老旧，但正在逐步翻新。",
    foodDesc: "燕南美食、学一食堂、艺园等，口味多样。北大小西门外的美食街也是好去处。",
    cityDesc: "北京，首都。高校云集，文化资源丰富。中关村科技创新氛围浓厚。",
    pros: ["学术氛围浓厚", "文理医全面", "人文学科顶尖", "校园风景优美"],
    cons: ["部分宿舍老旧", "冬季寒冷", "生活成本高"]
  },
  {
    id: 3,
    name: "浙江大学",
    tier: "985/211/双一流",
    rank: 3,
    city: "杭州",
    province: "浙江",
    lat: 30.2636,
    lng: 120.1236,
    minScore: 665,
    tags: ["综合", "工科强校", "创新创业"],
    majors: ["计算机科学与技术", "控制科学", "光学工程", "农学", "临床医学", "数学"],
    strengths: ["计算机", "控制", "光学", "农学", "临床医学"],
    teacherStrength: 93,
    campusEnv: 94,
    dormitory: 82,
    genderRatio: { male: 58, female: 42 },
    foodRating: 90,
    entertainment: 92,
    employmentRate: 97.5,
    avgSalary: "16,000+",
    description: "浙江大学坐落于"人间天堂"杭州，是一所特色鲜明、在海内外有较大影响的综合型、研究型大学。紫金港校区现代化程度高。",
    campusImages: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
      "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600"
    ],
    dormitoryDesc: "四人/三人间为主，紫金港校区宿舍较新，有空调、热水器。部分有独立卫浴。",
    foodDesc: "浙大食堂被誉为"亚洲第一大食堂"，紫金港校区的风味餐厅、留学生食堂等品种丰富。杭州美食天堂。",
    cityDesc: "杭州，互联网之都，阿里巴巴总部所在地。西湖美景，气候宜人。创新创业氛围浓厚，生活品质高。",
    pros: ["城市宜居", "创新创业氛围好", "校园现代化", "美食丰富"],
    cons: ["梅雨季节潮湿", "房价高", "交通拥堵"]
  },
  {
    id: 4,
    name: "武汉大学",
    tier: "985/211/双一流",
    rank: 8,
    city: "武汉",
    province: "湖北",
    lat: 30.5417,
    lng: 114.3643,
    minScore: 640,
    tags: ["综合", "樱花名校", "文理并重"],
    majors: ["测绘科学", "法学", "新闻传播", "水利工程", "生命科学", "经济学"],
    strengths: ["测绘", "法学", "新闻", "水利", "生物"],
    teacherStrength: 90,
    campusEnv: 97,
    dormitory: 78,
    genderRatio: { male: 51, female: 49 },
    foodRating: 92,
    entertainment: 90,
    employmentRate: 96.8,
    avgSalary: "14,000+",
    description: "武汉大学环绕东湖水，坐拥珞珈山，被誉为"中国最美丽的大学"。每年三月樱花盛开，吸引无数游客。学术实力雄厚。",
    campusImages: [
      "https://images.unsplash.com/photo-1580651315530-69c8e0026377?w=600",
      "https://images.unsplash.com/photo-1596987344673-9fbd6212ff18?w=600"
    ],
    dormitoryDesc: "四人/三人间为主，有空调。部分宿舍有独立卫浴，整体条件不错。",
    foodDesc: "武汉美食之都，热干面、豆皮、鸭脖。校内食堂众多，桂园食堂、梅园食堂等。",
    cityDesc: "武汉，九省通衢。高校云集（光谷有百万大学生），生活成本适中，城市有活力。夏天炎热。",
    pros: ["校园极美", "城市活力足", "生活成本适中", "美食天堂"],
    cons: ["夏季炎热", "城市较大", "部分地区嘈杂"]
  },
  {
    id: 5,
    name: "中山大学",
    tier: "985/211/双一流",
    rank: 10,
    city: "广州",
    province: "广东",
    lat: 23.1247,
    lng: 113.2964,
    minScore: 635,
    tags: ["综合", "华南第一", "医学强校"],
    majors: ["临床医学", "工商管理", "哲学", "海洋科学", "数学", "生态学"],
    strengths: ["临床医学", "工商管理", "哲学", "海洋科学"],
    teacherStrength: 88,
    campusEnv: 91,
    dormitory: 80,
    genderRatio: { male: 47, female: 53 },
    foodRating: 94,
    entertainment: 93,
    employmentRate: 96.5,
    avgSalary: "15,000+",
    description: "中山大学由孙中山先生创办，是华南地区最高学府。广州校区南校园（康乐园）古色古香，珠海校区依山傍海。",
    campusImages: [
      "https://images.unsplash.com/photo-1581079289196-67865ea83118?w=600",
      "https://images.unsplash.com/photo-1570710891163-6d3b5c47248b?w=600"
    ],
    dormitoryDesc: "四人间为主，有空调。珠海校区宿舍较新且条件好，部分有海景。",
    foodDesc: "食在广州！中大食堂粤菜正宗，烧腊、肠粉、煲仔饭等一应俱全。周边美食街更是选择丰富。",
    cityDesc: "广州，千年商都。美食之都，气候温暖。粤港澳大湾区核心城市，就业机会多。但夏天湿热。",
    pros: ["美食天堂", "气候温暖", "大湾区就业", "医学顶尖"],
    cons: ["夏天湿热", "回南天", "交通拥堵"]
  },
  {
    id: 6,
    name: "华中科技大学",
    tier: "985/211/双一流",
    rank: 7,
    city: "武汉",
    province: "湖北",
    lat: 30.5136,
    lng: 114.4178,
    minScore: 638,
    tags: ["工科强校", "医学突出", "综合"],
    majors: ["机械工程", "光学工程", "电气工程", "计算机科学", "临床医学", "公共卫生"],
    strengths: ["机械", "光学", "电气", "计算机", "临床医学"],
    teacherStrength: 89,
    campusEnv: 85,
    dormitory: 80,
    genderRatio: { male: 65, female: 35 },
    foodRating: 88,
    entertainment: 87,
    employmentRate: 97.0,
    avgSalary: "14,500+",
    description: "华中科技大学是工科和医学见长的综合性大学。同济医学院全国闻名。光谷核心位置，产学研结合紧密。",
    campusImages: [
      "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=600",
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600"
    ],
    dormitoryDesc: "四人间为主，有空调热水器。沁苑、韵苑等宿舍区条件良好。",
    foodDesc: "武汉美食汇聚，校内食堂选择多。韵苑大酒店（食堂）菜品丰富，价格实惠。",
    cityDesc: "武汉，光谷核心。百万大学生城市，生活成本友好。夏天较热但城市充满活力。",
    pros: ["工科医学强", "光谷就业好", "性价比高", "生活成本低"],
    cons: ["男女比例失衡", "夏季炎热", "校园较大"]
  },
  {
    id: 7,
    name: "四川大学",
    tier: "985/211/双一流",
    rank: 12,
    city: "成都",
    province: "四川",
    lat: 30.6316,
    lng: 104.0844,
    minScore: 620,
    tags: ["综合", "医学强校", "西部龙头"],
    majors: ["口腔医学", "临床医学", "材料科学", "数学", "中国语言文学", "生物医学工程"],
    strengths: ["口腔医学", "临床医学", "材料", "中文"],
    teacherStrength: 86,
    campusEnv: 88,
    dormitory: 78,
    genderRatio: { male: 45, female: 55 },
    foodRating: 97,
    entertainment: 96,
    employmentRate: 95.5,
    avgSalary: "12,500+",
    description: "四川大学是西南地区最高学府，华西医学中心全国闻名（口腔医学全国第一）。望江、华西、江安三校区各具特色。",
    campusImages: [
      "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600",
      "https://images.unsplash.com/photo-1570710891163-6d3b5c47248b?w=600"
    ],
    dormitoryDesc: "四人间为主，有空调。江安校区宿舍较新，条件不错。",
    foodDesc: "成都美食天下闻名！火锅、串串、担担面、钵钵鸡。川大周边美食街多不胜数。",
    cityDesc: "成都，天府之国。生活节奏慢，美食遍地，文化氛围浓厚。熊猫故乡，宜居之城。就业以西南为主。",
    pros: ["美食顶级", "生活安逸", "口腔医学全国第一", "文化氛围好"],
    cons: ["阴天多", "地震风险", "非一线城市"]
  },
  {
    id: 8,
    name: "西安交通大学",
    tier: "985/211/双一流/C9",
    rank: 14,
    city: "西安",
    province: "陕西",
    lat: 34.2453,
    lng: 108.9838,
    minScore: 630,
    tags: ["工科强校", "C9联盟", "西部龙头"],
    majors: ["电气工程", "动力工程", "机械工程", "管理科学", "核科学", "材料科学"],
    strengths: ["电气", "动力", "机械", "管理"],
    teacherStrength: 88,
    campusEnv: 84,
    dormitory: 76,
    genderRatio: { male: 63, female: 37 },
    foodRating: 90,
    entertainment: 82,
    employmentRate: 96.2,
    avgSalary: "13,500+",
    description: "西安交通大学是C9联盟成员，工科实力雄厚。兴庆校区毗邻兴庆宫公园，创新港校区现代化程度高。",
    campusImages: [
      "https://images.unsplash.com/photo-1562774053-701939374585?w=600",
      "https://images.unsplash.com/photo-1581079289196-67865ea83118?w=600"
    ],
    dormitoryDesc: "四人间为主，有空调暖气。创新港校区宿舍条件一流。",
    foodDesc: "西安美食丰富：肉夹馍、凉皮、羊肉泡馍、biangbiang面。食堂价格实惠。",
    cityDesc: "西安，十三朝古都。历史文化底蕴深厚，生活成本低。一带一路重要节点。冬天有暖气。",
    pros: ["C9名校", "生活成本低", "文化底蕴深厚", "冬季有暖气"],
    cons: ["地处西部", "男女比例失衡", "空气质量一般"]
  },
  {
    id: 9,
    name: "南京大学",
    tier: "985/211/双一流/C9",
    rank: 6,
    city: "南京",
    province: "江苏",
    lat: 32.0584,
    lng: 118.7965,
    minScore: 658,
    tags: ["综合", "文理强校", "C9联盟"],
    majors: ["天文学", "地质学", "物理学", "中国语言文学", "计算机科学", "环境科学"],
    strengths: ["天文", "地质", "物理", "中文", "计算机"],
    teacherStrength: 92,
    campusEnv: 93,
    dormitory: 79,
    genderRatio: { male: 49, female: 51 },
    foodRating: 86,
    entertainment: 87,
    employmentRate: 96.8,
    avgSalary: "15,500+",
    description: "南京大学是中国最顶尖的综合性大学之一，天文学全国第一。鼓楼校区古朴典雅，仙林校区现代大气。",
    campusImages: [
      "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=600",
      "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=600"
    ],
    dormitoryDesc: "四人/三人间，有空调。仙林校区宿舍条件较好，部分有独立卫浴。",
    foodDesc: "南京美食：盐水鸭、鸭血粉丝汤、小笼包。南大食堂品种丰富，价格适中。",
    cityDesc: "南京，六朝古都。历史文化底蕴深厚，高校云集。长三角核心城市，就业机会多。四季分明。",
    pros: ["学术严谨", "C9名校", "历史文化深厚", "长三角就业好"],
    cons: ["夏天炎热", "冬天湿冷", "生活成本中等"]
  },
  {
    id: 10,
    name: "厦门大学",
    tier: "985/211/双一流",
    rank: 20,
    city: "厦门",
    province: "福建",
    lat: 24.4397,
    lng: 118.0914,
    minScore: 625,
    tags: ["综合", "海景校园", "经济管理强"],
    majors: ["海洋科学", "化学", "经济学", "会计学", "统计学", "法学"],
    strengths: ["海洋科学", "化学", "经济", "会计"],
    teacherStrength: 83,
    campusEnv: 99,
    dormitory: 88,
    genderRatio: { male: 44, female: 56 },
    foodRating: 93,
    entertainment: 94,
    employmentRate: 95.8,
    avgSalary: "13,000+",
    description: "厦门大学被誉为"中国最美大学"，依山傍海，芙蓉湖畔风光旖旎。经济管理学科全国领先。",
    campusImages: [
      "https://images.unsplash.com/photo-1580651315530-69c8e0026377?w=600",
      "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600"
    ],
    dormitoryDesc: "四人间为主，有空调。海景宿舍是厦大一大特色，部分宿舍可看海。",
    foodDesc: "厦门美食：沙茶面、海蛎煎、姜母鸭。厦大食堂以勤业餐厅最为出名，海鲜丰富。",
    cityDesc: "厦门，海上花园。气候宜人，风景优美。旅游城市，生活品质高。但就业机会相比一线城市少。",
    pros: ["校园最美", "气候宜人", "生活品质高", "经济管理强"],
    cons: ["就业机会较少", "旅游城市物价偏高", "台风影响"]
  },
  {
    id: 11,
    name: "哈尔滨工业大学",
    tier: "985/211/双一流/C9",
    rank: 13,
    city: "哈尔滨",
    province: "黑龙江",
    lat: 45.7507,
    lng: 126.6432,
    minScore: 615,
    tags: ["工科强校", "C9联盟", "航天名校"],
    majors: ["航天工程", "机械工程", "材料科学", "计算机科学", "土木工程", "环境工程"],
    strengths: ["航天", "机械", "材料", "计算机"],
    teacherStrength: 87,
    campusEnv: 80,
    dormitory: 82,
    genderRatio: { male: 68, female: 32 },
    foodRating: 84,
    entertainment: 78,
    employmentRate: 96.0,
    avgSalary: "13,000+",
    description: "哈尔滨工业大学是C9联盟中工科实力最强的院校之一，航天、机器人等领域全国领先。深圳校区发展迅速。",
    campusImages: [
      "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600",
      "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=600"
    ],
    dormitoryDesc: "四人间为主，有暖气（必备！）。深圳校区宿舍条件更好。",
    foodDesc: "东北美食：锅包肉、杀猪菜、红肠、大列巴。食堂量大实惠，冬天还有冰糖葫芦。",
    cityDesc: "哈尔滨，冰城夏都。冬天非常冷但室内有暖气。俄罗斯风情浓厚。生活成本低。深圳校区可选择。",
    pros: ["C9名校", "工科超强", "生活成本低", "深圳校区可选"],
    cons: ["冬天极冷", "男女比例失衡", "地理位置偏"]
  },
  {
    id: 12,
    name: "复旦大学",
    tier: "985/211/双一流/C9",
    rank: 4,
    city: "上海",
    province: "上海",
    lat: 31.2989,
    lng: 121.4997,
    minScore: 670,
    tags: ["综合", "文理医强校", "C9联盟"],
    majors: ["新闻传播", "临床医学", "经济学", "哲学", "数学", "微电子"],
    strengths: ["新闻", "医学", "经济", "哲学", "数学"],
    teacherStrength: 95,
    campusEnv: 90,
    dormitory: 74,
    genderRatio: { male: 46, female: 54 },
    foodRating: 85,
    entertainment: 90,
    employmentRate: 97.2,
    avgSalary: "17,000+",
    description: "复旦大学是中国最顶尖的综合性大学之一，文科、医科全国领先。地处上海，国际化程度极高。",
    campusImages: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
      "https://images.unsplash.com/photo-1581079289196-67865ea83118?w=600"
    ],
    dormitoryDesc: "四人/三人间为主，有空调。邯郸校区宿舍条件一般，但地理位置好。",
    foodDesc: "复旦食堂以上海本帮菜和各地风味为主。五角场商圈美食选择丰富。",
    cityDesc: "上海，中国最大的国际化都市。就业机会多，文化资源丰富。生活成本高但机会也多。",
    pros: ["上海区位好", "国际化程度高", "文科医学顶尖", "就业前景好"],
    cons: ["生活成本高", "竞争激烈", "部分宿舍老旧"]
  }
];
